fixed incorrect log and the mount result checking

diff --git a/kooiot/factory-tlink/files/sbin/factory_make b/kooiot/factory-tlink/files/sbin/factory_make
--- a/kooiot/factory-tlink/files/sbin/factory_make
+++ b/kooiot/factory-tlink/files/sbin/factory_make
@@ -23,7 +23,6 @@ failure_show() {
 		fi
 	done
 	while [ "1" = "1" ]; do
-		echo "ERROR" > /dev/console
 		sleep 1
 	done
 }
@@ -55,9 +54,9 @@ tlink_make() {
 	if [ -e /mnt/factory-tlink ]; then
 		mkdir -p /mnt/data
 		mount /dev/mmcblk1p3 /mnt/data
-		if [ $? -eq 0 ]; then
-			echo "INSTALL FAILED!!!" > /dev/console
-			echo "INSTALL FAILED!!!" >> /tmp/tlink_make.log
+		if [ $? -ne 0 ]; then
+			echo "MOUNT FAILED!!!" > /dev/console
+			echo "MOUNT FAILED!!!" >> /tmp/tlink_make.log
 			failure_show
 		fi
 		mkdir -p /mnt/data/factory-tlink
